name: "Simple PR Size Labeler"
description: "Labels a Pull Request based on the number of changed lines"
author: "Alex Parra"

inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true


runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "tag"
  color: "blue"
