name: 'add-code-reviewers'
description: 'Action to add reviews to a pull request'
author: 'Alex Parra'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.reviewers-file-path }}
    - ${{ inputs.number }}

inputs:
  token:
    description: 'GitHub Token'
    required: true
  reviewers-file-path:
    description: 'Reviewers file'
    required: true
  number:
    description: 'Pull request number'
    required: true

outputs:
  reviewers:
    description: 'Reviewers added to the pull request'

branding:
  icon: 'thumbs-up'
  color: 'blue'