name: 'pr-sizer'
description: 'Action to add labels to a pull request based on the size of the changes'
author: 'Alex Parra'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.pr_number }}

inputs:
  token:
    description: 'GitHub Token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true

branding:
  icon: 'thumbs-up'
  color: 'blue'